python3 train.py  \
--exp-name get_config \
--batch-size 128 \
--nb-code 512 \
--resume-pth output/VQVAE/net_last.pth \
--vq-name VQVAE \
--out-dir experiments \
--lr-scheduler 150000 \
--lr 1.5e-5 \
--weight-decay 4.5e-2 \
--dataname t2m \
--down-t 2 \
--depth 3 \
--quantizer ema_reset \
--dilation-growth-rate 3 \
--vq-act relu \
--nodebug